#Should we start a test for player automatically after they join? They can start it manually with "/pingtest start" too
startTestOnJoin: false
#in seconds, approx
testDuration: 30
#How often should the player's ping be checked? this divided by test duration above will give you approx. how many times player ping will be checked
#in seconds
pingPollingFrequency: 2
#Send the latest ping info to player's actionbar (the thing above hotbar)
sendPolledToActionBar: true
#Kicks with a message containing avg ping, if false the avg ping gets sent to the player via chat
#Applies to both on join tests and manually started tests
kickAfterTest: false
